### ISSUE TITLE
File not found hyperSpec.mat

### ISSUE THREAD

**Issue by HarshAditya23** [namratadutt/LiDAR-and-Hyperspectral-Fusion-classification#1]
Muufl gulfport dataset do not have hyperSpec.mat file in it. and this line also is throwing an error.

# Hyperspectral data
hyper = hyper['hyperSpec']

Please help to solve this.

**Comment by namratadutt** [comment]
I apologize for the late response. I think I had a different file at that time. Here is the code to extract the hypercube from the mat file. Good luck!
```
# File directory
basedir = os.getcwd()
truth_file = basedir + "/muufl_gulfport_campus_1_hsi_220_label.mat"

# Read mat file
mat = scipy.io.loadmat(truth_file)

# Extract hypercube
hsi = ((mat['hsi'])[0])[0]
hyper = hsi[1] # hypercube
```

**Comment by HarshAditya23** [comment]
Can tell me how to generate classified output (classified map) as a result?? I tried using y_pred function but no luck.

Have you tried to use the program of 2018 Houston Data of Hyperspec & Lidar ?

**Comment by namratadutt** [comment]
Are you asking how to generate the classified/ segmented map of the entire ROI? I usually take this approach. I firstly flatten the hypercube pixels from (height x width x bands) --> ((height*width) x bands). Secondly, I make the predictions using the model.predict() function in Keras. Thirdly, I reshape the predictions back to (height x width).
